name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          release_branches: "main"
          custom_tag: "v1.0.0"

      - name: Get tag version
        id: get_version
        run: echo "::set-output name=tag_version::$(git describe --tags --abbrev=0)"

  build:
    needs: version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ai-cicd:latest
            ${{ secrets.DOCKER_USERNAME }}/ai-cicd:${{ needs.version.outputs.tag_version }}
            ${{ secrets.DOCKER_USERNAME }}/ai-cicd:${{ steps.extract_branch.outputs.branch }}

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy vulnerability scan on latest tag
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/ai-cicd:latest

      - name: Run Trivy vulnerability scan on version tag
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/ai-cicd:${{ needs.version.outputs.tag_version }}

      - name: Run Trivy vulnerability scan on branch tag
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/ai-cicd:${{ steps.extract_branch.outputs.branch }}